
# Option-1 : Createting docker container using command module 
---
- hosts: all
  become: true

  tasks:
  - name: creating docker image using docker command
    command: docker run -d --name hellow-world-container -p 8080:8080 hellow-world-image
	
# option-2 : creating docker container using docker_container module 	
#  tasks:
#  - name: create hellow-world-container
#    docker_container:
#      name: hellow-world-container
#      image: hellow-world-image
#      state: present
#      recreate: yes
#      ports:
#        - "8080"
