---
- hosts: all
  become: true
  tasks:
  - name: stop if we have old docker container
    command: docker stop hellow-world-container
    ignore_errors: yes

  - name: remove stopped docker container
    command: docker rm hellow-world-container
    ignore_errors: yes

  - name: remove current docker image
    command: docker rmi hellow-world-image
    ignore_errors: yes
#    register: result
#    failed_when:
#      - result.rc == 0
#      - '"docker" not in result.stdout'


  - name: building docker image
    command: docker build -t hellow-world-image .
    args:
      chdir: /opt/docker

  - name: creating docker image
    command: docker run -d --name hellow-world-container -p 8080:8080 hellow-world-image

